### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by misterch0c** [khalilbijjou/WAFNinja#3]
My report all shows working:"yes". I suppose it's because the WAF sends a code 200 (a page saying the request was blocked). So maybe parsing the response to check if it's a message from the WAF would be a good idea (:

**Comment by khalilbijjou** [comment]
@misterch0c, thank you for your suggestion!

1) Can you tell me which WAF you used WAFninja against? Maybe you can also send me the whole response. I will then consider wether to add further response checking.
2) WAFNinja's output also includes the "Content-Length" and the "Output" columns as further indicators for the user to analyze, whether a payload was blocked or not. You can use this information as a differentiator in the meantime.
