### ISSUE TITLE
what? firePayload

### ISSUE THREAD

**Issue by gitfuzzing** [khalilbijjou/WAFNinja#4]
Traceback (most recent call last):
  File "wafninja.py", line 15, in <module>
    from ninja.bypass import firePayload
  File "/Users/mac/Desktop/WAFNinja-master/ninja/bypass.py", line 16, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
macdeMacBook-Pro:WAFNinja-master mac$ python wafninja.py
Traceback (most recent call last):
  File "wafninja.py", line 15, in <module>
    from ninja.bypass import firePayload
  File "/Users/mac/Desktop/WAFNinja-master/ninja/bypass.py", line 16, in <module>
    from prettytable import PrettyTable

**Comment by khalilbijjou** [comment]
You have to install the two modules prettytable and processbar.

Use "pip install prettytable" and "pip install processbar". If pip is not in your system environment variable, look in the python folder under "Scripts".

**Comment by jedilinux** [comment]
Requirement already satisfied: prettytable==0.7.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.7.2)
Collecting progressbar==2.3
  Using cached progressbar-2.3.tar.gz (9.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k_kfakwy/progressbar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k_kfakwy/progressbar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2cq98h06
         cwd: /tmp/pip-install-k_kfakwy/progressbar/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k_kfakwy/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/tmp/pip-install-k_kfakwy/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/tmp/pip-install-k_kfakwy/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/usr/lib/python3.9/abc.py", line 85, in __new__
        cls = super().__new__(mcls, name, bases, namespace, **kwargs)
    ValueError: 'format' in __slots__ conflicts with class variable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jedilinux** [comment]
Requirement already satisfied: prettytable==0.7.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.7.2)
Requirement already satisfied: progressbar==2.5 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (2.5)
                                                                                                                                 
┌──(root💀kali)-[/home/jedi/WAFNinja]
└─# python wafninja.py fuzz -u "http://www.target.com/index.php?id=FUZZ"
Traceback (most recent call last):
  File "wafninja.py", line 15, in <module>
    from ninja.bypass import firePayload
  File "/home/jedi/WAFNinja/ninja/bypass.py", line 16, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable

**Comment by Bindhushankar** [comment]
Traceback (most recent call last):
File "wafninja.py", line 15, in
from ninja.bypass import firePayload
File "/home/jedi/WAFNinja/ninja/bypass.py", line 16, in
from prettytable import PrettyTable
ImportError: No module named prettytable

**Comment by Bindhushankar** [comment]
me too getting same error

**Comment by Diego-lab-source** [comment]
└─# pip install -r requirements.txt
Requirement already satisfied: prettytable==0.7.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.7.2)
Requirement already satisfied: progressbar==2.5 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (2.5)
                                                                                                                                 
┌──(root💀kali)-[/home/jedi/WAFNinja]
└─# ls
argument.py  argument.pyc  db  ninja  README.md  requirements.txt  wafninja.py
                                                                                                                                 
┌──(root💀kali)-[/home/jedi/WAFNinja]
└─# ./wafninja.py -h
./wafninja.py: 10: 

    :Program: WAFNinja
    :ModuleName: wafninja
    :Version: 1.0
    :Revision: 1.0.0
    :Author: Khalil Bijjou
    :Description: The wafninja module is the main module, that controls the flow of the program. 

: not found
: not foundpy: 11: 
./wafninja.py: 12: from: not found
./wafninja.py: 13: from: not found
./wafninja.py: 14: from: not found
./wafninja.py: 15: from: not found
./wafninja.py: 16: from: not found
: not foundpy: 17: 
./wafninja.py: 18: Syntax error: "(" unexpected
